In [1]:
import pandas as pd
import numpy as np
#Machine Learning Algo
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
#Split Dataset in training and testing
from sklearn.model_selection import train_test_split
#to evaluate classification model
from sklearn.metrics import accuracy_score, confusion_matrix
#Convert text column into numerical values
from sklearn.preprocessing import LabelEncoder

In [2]:
#Part A: Dataset Understanding
1)df = pd.read_csv("/content/Dataset 2.csv - Dataset 2.csv.csv")
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [3]:
2)print("Shape: ",df.shape)

Shape:  (750, 10)

In [5]:
3)print("Columns: ",df.columns)

Columns:  Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [6]:
4)print("Datatype: ",df.dtypes)

Datatype:  UserID                  int64
Age                     int64
Gender                 object
SubscriptionType       object
WatchHoursPerWeek       int64
DevicesUsed             int64
FavoriteGenre          object
AdClicks                int64
MonthlySpend            int64
SubscriptionRenewed    object
dtype: object

In [9]:
5)df.isnull().values.any()

np.False_

In [10]:
#Part B: Exploratory Data Analysis
6)print('Average Age:',round(df['Age'].mean()))

Average Age: 42

In [11]:
7)print('Average Watchhoursperweek:',round(df['WatchHoursPerWeek'].mean()))

Average Watchhoursperweek: 14

In [12]:
8)print('Average Monthly Spending:',round(df['MonthlySpend'].mean()))

Average Monthly Spending: 690

In [16]:
9)df['SubscriptionType'].value_counts()

SubscriptionType
0    342
1    279
2    129
Name: count, dtype: int64

In [17]:
10)df['SubscriptionRenewed'].value_counts(normalize=True) * 100

SubscriptionRenewed
No     53.733333
Yes    46.266667
Name: proportion, dtype: float64

In [37]:
#Part C: Data Preparation
11)le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['SubscriptionType']=le.fit_transform(df['SubscriptionType'])
df['FavoriteGenre']=le.fit_transform(df['FavoriteGenre'])
df['SubscriptionRenewed']=le.fit_transform(df['SubscriptionRenewed'])

In [22]:
12)y = df['SubscriptionRenewed']
x = df.drop(['UserID', 'SubscriptionRenewed'], axis=1)

In [23]:
13)x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
#Part D: Decision Tree Classification
14)dt = DecisionTreeClassifier(random_state=42)
dt.fit(x_train,y_train)
pred = dt.predict(x_test)

In [28]:
15)print('Decision Tree Accuracy:',accuracy_score(y_test,pred))

Decision Tree Accuracy: 1.0

In [29]:
16)print('\nConfusion Matrix')
print(confusion_matrix(y_test,pred))

Confusion Matrix
[[82  0]
 [ 0 68]]

In [31]:
#Part E: K-Nearest Neighbors (KNN)
17)knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
knn_pred = knn.predict(x_test)

In [33]:
18)print('KNN Accuracy:',accuracy_score(y_test,knn_pred))
print('Decision Tree Accuracy:',accuracy_score(y_test,pred))

KNN Accuracy: 0.6333333333333333
Decision Tree Accuracy: 1.0

In [45]:
#Part F: Linear Regression
19)df = df.drop(['SubcrptionRenewed', 'SubcriptionRenewed'], axis=1)
y_reg =  df['MonthlySpend']
x_reg = df.drop(['UserID', 'MonthlySpend'], axis=1)

x_train_reg,x_test_reg,y_train_reg,y_test_reg = train_test_split(x_reg,y_reg,test_size=0.2,random_state=42)
lr = LinearRegression()
lr.fit(x_train_reg,y_train_reg)
20)amount = lr.predict([[30,1,2,20,3,2,22,1]])
print('Predicted Spending:',amount[0])

Predicted Spending: 1342.7712652498924

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
#Buisness Reflection Questions
ans1) Age
Gender
SubscriptionType
WatchHoursPerWeek
DevicesUsed
FavoriteGenre
AdClicks
MonthlySpend
SubscriptionRenewed
ans2) because it gives output yes/no
ans3) it gives numerical output
ans4) Decision Tree
ans5) The platform can:

    1)Identify users likely to cancel before renewal.
    2)Send personalized offers or discounts.
    3)Recommend content based on favorite genres.
    4)Encourage engagement among low-watch-hour users.
    5)Upgrade high-engagement users to premium plans.
    6)Launch targeted marketing campaigns for at-risk customers.